spring:
  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

service:
  jwt:
    access-expiration: 3600000
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"

server:
  port: 19095

---

# dev 프로필 설정
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:test;
    driver-class-name: org.h2.Driver
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update

---

# prod 프로필 설정
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:h2:mem:test;
    driver-class-name: org.h2.Driver
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update