spring:
  application:
    name: server

server:
  port: 19090

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:19090/eureka/
    fetch-registry: false
  instance:
    hostname: localhost